"""Add DeFi models

Revision ID: 9077a7ba8a6a
Revises: 2024_01_01_extended_features
Create Date: 2026-04-09 16:12:09.359155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9077a7ba8a6a'
down_revision = '2024_01_01_extended_features'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.String(length=100), nullable=False),
    sa.Column('dao_name', sa.String(length=100), nullable=False),
    sa.Column('dao_logo', sa.String(length=255), nullable=True),
    sa.Column('blockchain', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('proposal_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('voting_start', sa.DateTime(), nullable=True),
    sa.Column('voting_end', sa.DateTime(), nullable=True),
    sa.Column('quorum', sa.Float(), nullable=True),
    sa.Column('current_quorum', sa.Float(), nullable=True),
    sa.Column('votes_for', sa.Float(), nullable=True),
    sa.Column('votes_against', sa.Float(), nullable=True),
    sa.Column('votes_abstain', sa.Float(), nullable=True),
    sa.Column('total_votes', sa.Float(), nullable=True),
    sa.Column('user_vote', sa.String(length=20), nullable=True),
    sa.Column('user_voting_power', sa.Float(), nullable=True),
    sa.Column('creator_address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_proposals_id'), 'governance_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_governance_proposals_proposal_id'), 'governance_proposals', ['proposal_id'], unique=True)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('price_change_24h', sa.Float(), nullable=True),
    sa.Column('price_change_percent_24h', sa.Float(), nullable=True),
    sa.Column('volume_change_24h', sa.Float(), nullable=True),
    sa.Column('fear_greed_index', sa.Float(), nullable=True),
    sa.Column('social_volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    op.create_index('ix_market_symbol_timestamp', 'market_data', ['symbol', 'timestamp'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_value_usd', sa.Float(), nullable=True),
    sa.Column('total_value_change_24h', sa.Float(), nullable=True),
    sa.Column('total_value_change_percent_24h', sa.Float(), nullable=True),
    sa.Column('daily_pnl', sa.Float(), nullable=True),
    sa.Column('weekly_pnl', sa.Float(), nullable=True),
    sa.Column('monthly_pnl', sa.Float(), nullable=True),
    sa.Column('all_time_pnl', sa.Float(), nullable=True),
    sa.Column('volatility_30d', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('asset_distribution', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=True)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=True),
    sa.Column('horizon', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('predicted_price', sa.Float(), nullable=True),
    sa.Column('predicted_change', sa.Float(), nullable=True),
    sa.Column('predicted_high', sa.Float(), nullable=True),
    sa.Column('predicted_low', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('volatility_prediction', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_symbol'), 'predictions', ['symbol'], unique=False)
    op.create_index('ix_predictions_symbol_horizon', 'predictions', ['symbol', 'horizon'], unique=False)
    op.create_index(op.f('ix_predictions_timestamp'), 'predictions', ['timestamp'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('achievement_id', sa.String(length=50), nullable=False),
    sa.Column('achievement_name', sa.String(length=100), nullable=False),
    sa.Column('achievement_description', sa.Text(), nullable=True),
    sa.Column('achievement_icon', sa.String(length=50), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('total_queries', sa.Integer(), nullable=True),
    sa.Column('total_chats', sa.Integer(), nullable=True),
    sa.Column('total_models_viewed', sa.Integer(), nullable=True),
    sa.Column('total_favorites', sa.Integer(), nullable=True),
    sa.Column('total_tokens_earned', sa.Float(), nullable=True),
    sa.Column('total_tokens_spent', sa.Float(), nullable=True),
    sa.Column('total_tokens_claimed', sa.Float(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('experience_to_next_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stats_id'), 'user_stats', ['id'], unique=False)
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('blockchain', sa.String(length=50), nullable=True),
    sa.Column('contract_address', sa.String(length=100), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('average_buy_price', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('cost_basis', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl_percent', sa.Float(), nullable=True),
    sa.Column('price_change_24h', sa.Float(), nullable=True),
    sa.Column('price_change_percent_24h', sa.Float(), nullable=True),
    sa.Column('is_staked', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_portfolio_id'), 'assets', ['portfolio_id'], unique=False)
    op.create_index('ix_assets_portfolio_symbol', 'assets', ['portfolio_id', 'symbol'], unique=False)
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_table('liquidity_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('protocol_name', sa.String(length=100), nullable=False),
    sa.Column('pool_name', sa.String(length=100), nullable=False),
    sa.Column('pool_address', sa.String(length=100), nullable=True),
    sa.Column('blockchain', sa.String(length=50), nullable=False),
    sa.Column('token0_symbol', sa.String(length=20), nullable=False),
    sa.Column('token0_amount', sa.Float(), nullable=True),
    sa.Column('token0_value_usd', sa.Float(), nullable=True),
    sa.Column('token1_symbol', sa.String(length=20), nullable=False),
    sa.Column('token1_amount', sa.Float(), nullable=True),
    sa.Column('token1_value_usd', sa.Float(), nullable=True),
    sa.Column('lp_token_amount', sa.Float(), nullable=True),
    sa.Column('lp_token_value_usd', sa.Float(), nullable=True),
    sa.Column('share_of_pool', sa.Float(), nullable=True),
    sa.Column('reward_asset_symbol', sa.String(length=20), nullable=True),
    sa.Column('pending_rewards', sa.Float(), nullable=True),
    sa.Column('total_rewards_earned', sa.Float(), nullable=True),
    sa.Column('apy', sa.Float(), nullable=True),
    sa.Column('impermanent_loss_percent', sa.Float(), nullable=True),
    sa.Column('position_start_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidity_positions_id'), 'liquidity_positions', ['id'], unique=False)
    op.create_index(op.f('ix_liquidity_positions_portfolio_id'), 'liquidity_positions', ['portfolio_id'], unique=False)
    op.create_table('model_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('uptime_percentage', sa.Float(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_statuses_checked_at'), 'model_statuses', ['checked_at'], unique=False)
    op.create_index(op.f('ix_model_statuses_id'), 'model_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_model_statuses_model_id'), 'model_statuses', ['model_id'], unique=True)
    op.create_table('staking_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('protocol_name', sa.String(length=100), nullable=False),
    sa.Column('protocol_url', sa.String(length=255), nullable=True),
    sa.Column('blockchain', sa.String(length=50), nullable=False),
    sa.Column('staked_asset_symbol', sa.String(length=20), nullable=False),
    sa.Column('staked_asset_name', sa.String(length=100), nullable=False),
    sa.Column('staked_amount', sa.Float(), nullable=True),
    sa.Column('reward_asset_symbol', sa.String(length=20), nullable=True),
    sa.Column('reward_asset_name', sa.String(length=100), nullable=True),
    sa.Column('pending_rewards', sa.Float(), nullable=True),
    sa.Column('total_rewards_earned', sa.Float(), nullable=True),
    sa.Column('apy', sa.Float(), nullable=True),
    sa.Column('apr', sa.Float(), nullable=True),
    sa.Column('staked_value_usd', sa.Float(), nullable=True),
    sa.Column('rewards_value_usd', sa.Float(), nullable=True),
    sa.Column('total_value_usd', sa.Float(), nullable=True),
    sa.Column('lock_period_days', sa.Integer(), nullable=True),
    sa.Column('unlock_date', sa.DateTime(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('position_start_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staking_positions_id'), 'staking_positions', ['id'], unique=False)
    op.create_index(op.f('ix_staking_positions_portfolio_id'), 'staking_positions', ['portfolio_id'], unique=False)
    op.drop_index(op.f('ix_notifications_user_read'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_model_reviews_created_at'), table_name='model_reviews')
    op.drop_index(op.f('ix_model_reviews_user_id'), table_name='model_reviews')
    op.drop_index(op.f('ix_reviews_user_model'), table_name='model_reviews')
    op.drop_table('model_reviews')
    op.drop_index(op.f('ix_webhooks_user_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_collection_items_collection_model'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_model_playbooks_category'), table_name='model_playbooks')
    op.drop_index(op.f('ix_model_playbooks_user_id'), table_name='model_playbooks')
    op.drop_table('model_playbooks')
    op.drop_index(op.f('ix_collections_user'), table_name='collections')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_export_jobs_user_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_model_comparisons_user_id'), table_name='model_comparisons')
    op.drop_table('model_comparisons')
    op.drop_index(op.f('ix_favorites_user_model'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_created_at'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_notification_subscriptions_user_id'), table_name='notification_subscriptions')
    op.drop_index(op.f('ix_subscriptions_user_type'), table_name='notification_subscriptions')
    op.drop_table('notification_subscriptions')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_provider_user'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=False),
    sa.Column('provider_user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('access_token', sa.VARCHAR(length=500), nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=500), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('scopes', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_provider_user'), 'oauth_accounts', ['provider', 'provider_user_id'], unique=1)
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('notification_subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('subscription_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_type'), 'notification_subscriptions', ['user_id', 'subscription_type'], unique=1)
    op.create_index(op.f('ix_notification_subscriptions_user_id'), 'notification_subscriptions', ['user_id'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('model_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_created_at'), 'user_favorites', ['created_at'], unique=False)
    op.create_index(op.f('ix_favorites_user_model'), 'user_favorites', ['user_id', 'model_id'], unique=1)
    op.create_table('model_comparisons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('model_ids', sqlite.JSON(), nullable=False),
    sa.Column('comparison_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_comparisons_user_id'), 'model_comparisons', ['user_id'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('export_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('format', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('download_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_user_id'), 'export_jobs', ['user_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('cover_image', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_index(op.f('ix_collections_user'), 'collections', ['user_id', 'is_public'], unique=False)
    op.create_table('model_playbooks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('model_id', sa.INTEGER(), nullable=True),
    sa.Column('prompt_template', sa.TEXT(), nullable=False),
    sa.Column('example_input', sa.TEXT(), nullable=True),
    sa.Column('example_output', sa.TEXT(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_playbooks_user_id'), 'model_playbooks', ['user_id'], unique=False)
    op.create_index(op.f('ix_model_playbooks_category'), 'model_playbooks', ['category'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('collection_id', sa.INTEGER(), nullable=False),
    sa.Column('model_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_items_collection_model'), 'collection_items', ['collection_id', 'model_id'], unique=1)
    op.create_table('webhooks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('secret', sa.VARCHAR(length=100), nullable=False),
    sa.Column('events', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('last_triggered', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_user_id'), 'webhooks', ['user_id'], unique=False)
    op.create_table('model_reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('model_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('pros', sa.TEXT(), nullable=True),
    sa.Column('cons', sa.TEXT(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('helpful_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_user_model'), 'model_reviews', ['user_id', 'model_id'], unique=1)
    op.create_index(op.f('ix_model_reviews_user_id'), 'model_reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_model_reviews_created_at'), 'model_reviews', ['created_at'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('session_token', sa.VARCHAR(length=255), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_activity', sa.DATETIME(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=1)
    op.create_table('user_notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('is_sent', sa.BOOLEAN(), nullable=True),
    sa.Column('sent_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_read'), 'user_notifications', ['user_id', 'is_read'], unique=False)
    op.drop_index(op.f('ix_staking_positions_portfolio_id'), table_name='staking_positions')
    op.drop_index(op.f('ix_staking_positions_id'), table_name='staking_positions')
    op.drop_table('staking_positions')
    op.drop_index(op.f('ix_model_statuses_model_id'), table_name='model_statuses')
    op.drop_index(op.f('ix_model_statuses_id'), table_name='model_statuses')
    op.drop_index(op.f('ix_model_statuses_checked_at'), table_name='model_statuses')
    op.drop_table('model_statuses')
    op.drop_index(op.f('ix_liquidity_positions_portfolio_id'), table_name='liquidity_positions')
    op.drop_index(op.f('ix_liquidity_positions_id'), table_name='liquidity_positions')
    op.drop_table('liquidity_positions')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_index('ix_assets_portfolio_symbol', table_name='assets')
    op.drop_index(op.f('ix_assets_portfolio_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_index(op.f('ix_user_stats_id'), table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_predictions_timestamp'), table_name='predictions')
    op.drop_index('ix_predictions_symbol_horizon', table_name='predictions')
    op.drop_index(op.f('ix_predictions_symbol'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index('ix_market_symbol_timestamp', table_name='market_data')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_governance_proposals_proposal_id'), table_name='governance_proposals')
    op.drop_index(op.f('ix_governance_proposals_id'), table_name='governance_proposals')
    op.drop_table('governance_proposals')
    # ### end Alembic commands ###
